server:
  port: 8080

spring:
  application:
    name: "finalproject"
  main:
    banner-mode: "log"
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://XXX/autoservice
    username: XXX
    password: XXX
jpa:
  generate-ddl: true
  hibernate:
    hbm2ddl-auto: update
  show-sql: true
  database: postgresql

logging:
  level:
    org:
      springframework: ERROR
