server:
  port: 8080
  #context-path: /rest

spring:
  application:
    name: "laptop"
  main:
    banner-mode: "off"
  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
jpa:
  generate-ddl: true
  hibernate:
    ddl-auto: update
  database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      springframework: ERROR